global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          scheme: http
          timeout: 10s
          api_version: v1
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    honor_timestamps: true
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - localhost:9090